http://localhost:3000/notes
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyLCJpYXQiOjE3MTA3NzYzMDUsImV4cCI6MTcxMDc3OTkwNX0.qnFWXth1fOc4jon6hOBuoHnVaA7_JM1uXmLNim2IOUI